<?php foreach($comments as $comment):?>

            <fieldset class="comment">
    <legend> <i class="fa fa-comment" aria-hidden="true"></i>
        <?=$comment['titre']?>
    </legend>
    <?=$comment['commentaire']?>
        <hr> <small>
                        Posté le <?=$comment['date_post']?> 
                        par : <?=$comment['pseudo']?>
                    </small> 
</fieldset>
 <?php endforeach;?>