<header>
        <nav>
            <ul class="container">
            <li><a href="../index.php">Accueil</a></li>
            
            
        <?php
            if(!empty($categories)):
            foreach($categories as $category):
        ?>
            <li>
                <a href="#" class="categ" data-id="<?=$category['id']?>">
                    <?=$category['libelle']?>
                </a>
            </li>
        <?php
            endforeach;
            
            else:
        ?>
           <li id="new"><a href="postcreate.php">Nouveau post</a></li>
        <?php endif;?>
            </ul>
        </nav>
</header>