<?php foreach($posts as $post):?>
              
               <div class="post">
                  <h3><?=$post['title']?></h3>
                   <p><?=shortenText($post['content'],250)?></p>
                   <small><a href="inc/getOnePost.php?id=<?=$post['id']?>">Lire la suite -></a></small>
                   <br/>
                   <small>Par : <?=$post['pseudo']?> le : <?=$post['date_creation']?> dans: <i class="fa fa-tag" aria-hidden="true"></i> <?=$post['libelle']?> </small>
               </div>
               <hr>
           <?php endforeach;?>