<form method="POST" action="" class="generic-form">
    <fieldset>
        <legend><i class="fa fa-lock" aria-hidden="true"></i> Informations d'authentification</legend>
        <label for="email">Email :</label>
        <input id="email" type="email" name="email" required>

        <label for="pwd">Mot de passe :</label>
        <input id="pwd" type="password" name="pwd" required>
    </fieldset>

    <input type="submit" value="Connexion"  class="button button-primary">
</form>