<form method="POST" action="" class="generic-form">
    <fieldset>
        <legend><i class="fa fa-lock" aria-hidden="true"></i> Réservation</legend>
        <label for="bookingDate">Date de la réservation :</label>
        <input id="bookingDate" type="date" name="bookingDate" required>

        <label for="bookingTime">Heure de la réservation :</label>
        <input id="bookingTime" type="time" name="bookingTime" required>

        <label for="bookingSeats">Nombre de personnes :</label>
        <input id="bookingSeats" type="number" name="bookingSeats" required>
        <input type="submit" value="Envoyer" class="button">
    </fieldset>

</form>

