<!DOCTYPE html>
<html lang="fr">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>PHP</title>
</head>
<body>
<h1>3WA Painter</h1>
<svg height="600px" width="800px">
    <rect x="50" y="20" width="200" height="100" fill="firebrick" opacity="1"></rect>
    <rect x="400" y="200" width="100" height="100" fill="deepskyblue" opacity="0.5"></rect>
    <circle cx="300" cy="250" r="180" fill="gold" opacity="0.33"></circle>
    <ellipse cx="600" cy="180" rx="40" ry="80" fill="seagreen" opacity="1"></ellipse>
    <polygon points="60 60,200 250,60 250" fill="purple" opacity="0.75"></polygon>
</svg>
</body>
</html>