<!-- Message de notification -->

<!-- Code HTML à écrire -->

<form action="index.php/user">
    <input type="submit" value="Inscription" class="button button-primary">
</form>
<!-- Liste des aliments -->
<table class="generic-table meal-list">
    <caption>Carte du restaurant</caption>
    <tbody>
    <?php foreach($meals as $meal): ?>
        <tr>
            <td><img src="<?= $wwwUrl ?>/images/meals/<?= $meal['Photo']; ?>" alt="<?= $meal['Name']; ?>"></td>
            <td>
                <strong><?= $meal['Name']; ?></strong>
                <p><?= $meal['Description']; ?></p>
            </td>
            <td class="number"><strong><?= number_format($meal['SalePrice'], 2) ?></strong> €</td>
        </tr>
    <?php endforeach; ?>
    </tbody>
</table>