<!-- Message de notification -->

<!-- Code HTML à écrire -->
<?php if(isset($isConnected)&&$isConnected==true):?>
<?=$userIdentity.'</br></br>'?>
    <a href="index.php/admin/users" class="button button-primary">Liste des utilisateurs</a>
    <a href="index.php/admin/meals" class="button button-primary">Liste des menus</a>
    <a href="index.php/admin/bookings" class="button button-primary">Liste des réservations</a>
    <a href="index.php/booking" class="button button-primary">Réservation</a>
    <a href="index.php/meal" class="button button-primary">Commande</a>
    <a href="index.php/basket" class="button button-primary">Mon Panier</a>
    <a href="index.php/user/logout" class="button button-cancel">Déconnexion</a>

<?php else:?>
    <a href="index.php/user" class="button button-primary">Inscription</a>
    <a href="index.php/user/login" class="button button-primary">Connexion</a>
<?php endif;?>

<!-- Liste des aliments -->
<table class="generic-table meal-list">
    <caption>Carte du restaurant</caption>
    <tbody>
    <?php foreach($meals as $meal): ?>
        <tr>
            <td><img src="<?= $wwwUrl ?>/images/meals/<?= $meal['Photo']; ?>" alt="<?= $meal['Name']; ?>"></td>
            <td>
                <strong><?= $meal['Name']; ?></strong>
                <p><?= $meal['Description']; ?></p>
            </td>
            <td class="number"><strong><?= number_format($meal['SalePrice'], 2) ?></strong> €</td>
        </tr>
    <?php endforeach; ?>
    </tbody>
</table>