<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>3WA Restaurant</title>
    <link rel="stylesheet" href="<?= $wwwUrl ?>/css/normalize-3.0.3.min.css">
    <link rel="stylesheet" href="<?= $wwwUrl ?>/css/font-awesome-4.3.0.min.css">

    <!-- Feuilles de styles de l'application -->
    <link rel="stylesheet" href="<?= $wwwUrl ?>/css/3wa-resto.css">
    <link rel="stylesheet" href="<?= $wwwUrl ?>/css/ui-button.css">
    <link rel="stylesheet" href="<?= $wwwUrl ?>/css/ui-form.css">
    <link rel="stylesheet" href="<?= $wwwUrl ?>/css/ui-table.css">
    <link rel="stylesheet" href="http://fonts.googleapis.com/css?family=Oleo+Script+Swash+Caps|Karla">

    <!-- Librairie jQuery -->
    <script src="http://code.jquery.com/jquery-2.1.0.min.js"></script>

    <!-- JavaScript de l'application -->
    <script src="<?= $wwwUrl ?>/js/utilities.js"></script>
</head>
<body>

<!-- En-tête commune -->
<header>
    <h1>
        <a href="<?= $requestUrl ?>">
            <img src="<?= $wwwUrl ?>/images/logo.gif" height="63" width="57" alt="3WA Restaurant">Restaurant - Made In America !
        </a>
    </h1>
</header>

<!-- Interface utilisateur -->
<nav class="user-interface">
    <ul class="link-list">
        <?php if(isset($isConnected)&&$isConnected==true):?>
            <?=$userIdentity.'</br></br>'?>
            <a href="<?=$requestUrl;?>/admin/users" class="button button-primary">Liste des utilisateurs</a>
            <a href="<?=$requestUrl;?>/admin/meals" class="button button-primary">Liste des menus</a>
            <a href="<?=$requestUrl;?>/admin/bookings" class="button button-primary">Liste des réservations</a>
            <a href="<?=$requestUrl;?>/booking" class="button button-primary">Réservation</a>
            <a href="<?=$requestUrl;?>/meal" class="button button-primary">Commande</a>
            <a href="<?=$requestUrl;?>/basket" class="button button-primary">Mon Panier</a>
            <a href="<?=$requestUrl;?>/user/logout" class="button button-cancel">Déconnexion</a>

        <?php else:?>
            <a href="<?=$requestUrl;?>/user" class="button button-primary">Inscription</a>
            <a href="<?=$requestUrl;?>/user/login" class="button button-primary">Connexion</a>
        <?php endif;?>
    </ul>
</nav>

<main>
    <!-- Affichage du template lié à la vue -->
    <?php include $this->viewData['template'] ?>
</main>

<!-- Pied de page commun -->
<footer>
    <ul class="link-list">
        <li><img src="<?= $wwwUrl ?>/images/payment/visa.png" alt="Visa"></li>
        <li><img src="<?= $wwwUrl ?>/images/payment/mastercard.png" alt="MasterCard"></li>
        <li><img src="<?= $wwwUrl ?>/images/payment/paypal.png" alt="PayPal"></li>
    </ul>
    <small>Réalisé avec <i class="fa fa-heart"></i>&nbsp; par les élèves de la 3W Academy</small>
</footer>

<!-- Code principal JavaScript de l'application -->
<script src="<?= $wwwUrl ?>/js/main.js"></script>
<script src="<?= $wwwUrl ?>/js/classes/FormValidator.class.js"></script>
</body>
</html>