<?php

if (isset($isConnected) && $isConnected == true):
    header('Location:../'); ?>
<?php else: ?>
    <a href="../" class="button button-cancel">Annuler</a>
    <a href="user/login" class="button button-primary">Connexion</a>
<?php endif; ?>
<h2>Création d'un compte client</h2>
<?php

if (isset($error_message) && !empty($error_message)) {
    echo $error_message;
}

?>

<form method="POST" action="" class="generic-form">
    <fieldset class="error-message">

    </fieldset>
    <fieldset>
        <legend><i class="fa fa-lock" aria-hidden="true"></i> Informations d'authentification</legend>
        <label for="email">Email :</label>
        <input id="email" data-name="email" data-length="20" type="email" name="email" >

        <label for="pwd">Mot de passe :</label>
        <input id="pwd" data-name="pwd" data-length="8" type="password" name="pwd" >
    </fieldset>
    <fieldset>
        <legend><i class="fa fa-book" aria-hidden="true"></i> Coordonées et informations complémentaires</legend>
        <label for="firstName">Prénom :</label>
        <input id="firstName" type="text" name="firstName" >

        <label for="lastName">Nom :</label>
        <input id="lastName" type="text" name="lastName" >


        <label for="birthDate">Date de naissance :</label>
        <input id="birthDate" type="date" name="birthDate" >

        <label for="address">Adresse :</label>
        <input id="address" type="text" name="address" >

        <label for="city">Ville :</label>
        <input id="city" type="text" name="city" >

        <label for="zipCode">Code Postal :</label>
        <input id="zipCode" type="text" name="zipCode" class="zip-code" >

        <label for="country">Pays :</label>
        <select name="country" >
            <option value="France">France</option>
            <option value="Espagne">Espagne</option>
            <option value="Royaume-Uni">Royaume-Uni</option>
            <option value="Allemagne">Allemagne</option>
        </select>

        <label for="phone">Téléphone :</label>
        <input id="phone" type="tel" name="phone" class="phone" >

        <input type="submit" value="Envoyer" class="button" id="inscription">
    </fieldset>

</form>

