<!-- Liste des aliments -->
<table class="generic-table">
    <caption>Liste des réservations</caption>
    <thead>
    <tr>
        <th>Id</th>
        <th>Date de réservation</th>
        <th>Heure de réservation</th>
        <th>Nombre de personnes</th>
        <th>Id Utilisateur</th>
        <th>Date de création</th>


    </tr>

    </thead>
    <tbody>
    <?php foreach ($bookings as $booking): ?>
        <tr>
            <td><?= $booking['Id'] ?></td>
            <td><?= $booking['BookingDate'] ?></td>
            <td><?= $booking['BookingTime'] ?></td>
            <td><?= $booking['NumberOfSeats'] ?></td>
            <td><?= $booking['User_Id'] ?></td>
            <td><?= $booking['CreationTimestamp'] ?></td>
            <td><a href="users?id=<?=$booking['Id']?>"><i class="fa fa-trash-o" aria-hidden="true"></i></a></td>
        </tr>
    <?php endforeach; ?>
    </tbody>
</table>