<div class="fiche_article">
    <select name="menu" id="meal">
        <?php foreach ((array)$meals as $meal) { ?>
            <option value="<?= $meal['Id'];?>"><?= $meal['Name'];?></option>
        <?php } ?>
    </select>

    <div class="half">
        <div id="designation" class="meal-details"></div>
        <img src="" id="photo" />
    </div>
    <div class="half">
        <div><span id="tarif"></span> € / unité</div>
        <div>Soit un total de <span id="total"></span></div>
        <div id="description" class="meal-details"></div>
        <div class="action">
            <select name="qte">
                <option>1</option>
                <option>2</option>
                <option>3</option>
                <option>4</option>
                <option>5</option>
                <option>6</option>
                <option>7</option>
                <option>8</option>
                <option>9</option>
                <option>10</option>
            </select>
            <input type="button" value="Ajouter au panier" id="add_panier" />
        </div>
    </div>
</div>
<div id="my_basket"></div>

<a href="order" class="button button-primary"> Valider le panier</a>
