<div id="my_basket">
<table class="generic-table">
    <thead>
    <tr>
        <th>Designation</th>
        <th>Prix unitaire</th>
        <th>Quantite</th>
        <th>Total</th>
        <td><td>
    </tr>
    </thead>
    <tbody>
    <?php
    $fTTC = 0;
    foreach ($basket as $aInfosBasket) :
        $fTotalItem = $aInfosBasket['SalePrice']*$aInfosBasket['Qte'];
        $fTTC += $fTotalItem;
        ?>
        <tr data-id=<?= (int) $aInfosBasket['Id'];?>>
            <td><?= htmlspecialchars($aInfosBasket['Name']);?></td>
            <td><?= htmlspecialchars($aInfosBasket['SalePrice']);?></td>
            <td><?= htmlspecialchars($aInfosBasket['Qte']);?></td>
            <td><?= $fTotalItem;?></td>
            <td><i class="fa fa-trash"></i></td>
        </tr>
    <?php endforeach; ?>
    </tbody>
    <tfoot>
    <tr><td colspan="4">Soit un TTC de <?= $fTTC;?> €</td></tr>
    </tfoot>
</table>

</div>